version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: blindtest-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sly
      POSTGRES_PASSWORD: slypass
      POSTGRES_DB: blindtest
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: blindtest-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@blindtest.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  pg_data:
